sonar.projectKey=bogdansharp_blood-cvrp
sonar.organization=bogdansharp

sonar.sources=backend/src,backend/seed,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=frontend/node_modules/**,frontend/build/**,frontend/.svelte-kit/**,backend/storage/**,storage/**,**/__pycache__/**,backend/.venv/**

sonar.python.version=3.12
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml